# Produces /tmp/vm.yaml based on selected plan and entered parameters
---
# TODO: fetch template from API once loaded at deployment
# TODO: Proper Linux and Windows templates are not yet ready, using the latest available
- name: Fetch template
  copy:
    src: templates/vm-template-rhel7.yaml
    dest: /tmp/vmtemplate.yaml

- name: Generate virtual machine {{ NAME }} with {{ MEMORY }}M of memory
  shell: "oc process -f /tmp/vmtemplate.yaml -pNAME={{ NAME }} -pMEMORY={{ MEMORY }}M -pCPU_CORES={{ CPU_CORES }} > /tmp/vm.yaml"
